# Generated by Django 3.2.6 on 2024-09-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyform',
            name='invoice_file_link',
        ),
        migrations.AddField(
            model_name='warrantyform',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('Carrier', 'Carrier'), ('Ferguson', 'Ferguson'), ('Goodman', 'Goodman'), ('Honeywell', 'Honeywell'), ('Lennox', 'Lennox'), ('Mitsubishi', 'Mitsubishi'), ('Trane', 'Trane'), ('Quality Air', 'Quality Air')], max_length=100, null=True),
        ),
    ]
