# Generated by Django 3.2.6 on 2024-09-23 16:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240922_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 23, 16, 29, 3, 287236, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
