# Generated by Django 3.2.6 on 2024-09-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_warrantyform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyform',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
