# Generated by Django 3.2.6 on 2024-09-23 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_warrantyform_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyform',
            name='test',
        ),
        migrations.AddField(
            model_name='warrantyform',
            name='add_time',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 9, 23, 18, 21, 29, 660215, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
