# Generated by Django 3.2.6 on 2024-09-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20240923_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warrantyform',
            old_name='add_time',
            new_name='creation_time',
        ),
    ]
